DECISION_TREE_GRID: str = 'DecisionTreeWithGrid'
RANDOM_FOREST_GRID: str = 'RandomForestWithGrid'
PERCEPTRON: str = 'Perceptron'
PERCEPTRON_2: str = 'Perceptron_2'
MLP: str = 'MLP'
MLP_2: str = 'MLP_2'
FFNN: str = 'FFNN'
FFNN_2: str = 'FFNN_2'
FFNN_3: str = 'FFNN_3'
FFNN_4: str = 'FFNN_4'
FFNN_5: str = 'FFNN_5'
FFNN_6: str = 'FFNN_6'
FFNN_7: str = 'FFNN_7'
FFNN_8: str = 'FFNN_8'

CNN: str = 'CNN'
