dist: trusty
git:
  depth: false
addons:
  sonarcloud:
    organization: "micheleantonazzi"
    token:
      secure: "z0TeKoC8WD/sJtPrtSPKxryCP32vJnEb+QBExCOsytZMtCXXqs1SnrXJNZc5KOJDJg6fe/WKyg/8psRMgML7yg6P/LxRiMMc2dAj7h6W1CJ8yznIgw8MddlJVPTToRaCAJdx2Uud8RVkiWqIVoO9t6wgwO4Qdni0XlFAPD22ldVL+2cGHL2GUa1VaL9FMEVICAeW3efLs1qh//WJ4JmcP9dTvb7tBsUIJ+dQCYHgX2rNwcw2OC1+0xKJSyNfvOgftnukaMFPmrwl2vEU5ilgq7iZaFb5FW4aXq5/Zhoyg62nMflKAJVBprscVk/R/4mOepkkbTkHW4HIx6hPJaVxVTnMwU10JBAKF7BmuHEkBuOkrJsrve4iGDVlJwCaYM7NLKk8RITPZlXJXfIzX5JQc7fhnWlM/KIEYmjSd9aVJuXo3n7jyZ9ZYrqdfe5QyWn9rOdD//ro1PcrHhPT9/VFs2u36Uv408D2JiZ/fZS9JdefqsrSRIgwczowUg6GsQJ+6gtoZepuGRk3EtAe1E+tFT0WhIni1U78B+VcASRY7tPgdfhtnaga1EYgNf/DytcqFgX7KSJyH9nTNmWBafTvBNa/hfmwK4ATjyhY+bJ6zFTj0d1t7jIgVczS2BLDRdtGnwxGQxhjSxcdBjxk1dbFz7BuWa+892ReOf4Ot71K+3c="
language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
  - pip install --upgrade pip setuptools wheel
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=bioinformatics_project --cov-report xml:coverage.xml 
- coverage combine --append || true
- coverage report
- coverage xml
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
